//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// DBInpSub.rc で使用
//
#define IDC_BTN_REG                     3
#define IDC_TKYREG                      3
#define IDR_MAINFRAME                   128
#define IDD_SCANKEY_DLG                 130
#define IDD_TEKIYO_DLG                  131
#define IDD_DLG_TKDIC                   132
#define IDD_TKSRCH_DLG                  138
#define IDD_SYKBN_DLG                   139
#define IDD_DLG_FURI                    140
#define IDR_SUBACCELERATOR              141
#define IDD_DLG_SWKSEL                  144
#define IDD_DLG_SWLISTSEL               147
#define IDD_DLG_EDAREG                  150
#define IDD_DLG_SWKTK                   151
#define IDD_DLG_RENTK                   152
#define IDD_KSRCSTR                     153
#define IDB_HUSEN_BMP                   155
#define IDD_SELDLG1                     155
#define IDD_FORKSEL                     156
#define IDD_HUSEN_DLG                   160
#define IDD_DLG_DNP                     161
#define IDD_DLG_NSKIN                   170
#define IDR_DNPCPYMENU                  190
#define IDC_TAB1                        1000
#define IDC_ICSDBEDTPAGE                1001
#define IDC_ICSDBEDT_NUM                1002
#define IDC_STATIC4                     1003
#define IDC_STATIC8                     1004
#define IDC_STATIC5                     1005
#define IDC_STATIC9                     1006
#define IDC_ST_REGCNT                   1007
#define IDC_STATIC10                    1008
#define IDC_BMNINP_CHK                  1009
#define IDC_ST_REGMAX                   1010
#define IDC_ST_DEBT                     1011
#define IDC_STDSP_RGCNT                 1012
#define IDC_ST_CRED                     1013
#define IDC_STDSP_RGMAX                 1014
#define IDC_ST_DBCR                     1015
#define IDC_STATIC_DSP                  1016
#define IDC_ST_VAL                      1017
#define IDC_ICSDBEDTKANA                1018
#define IDC_ST_ZEI                      1019
#define IDC_ST_SYZSW                    1020
#define IDC_ST_TKY                      1021
#define IDC_ST_DBR                      1022
#define IDC_SELLIST                     1023
#define IDC_ST_CBR                      1024
#define IDC_ST_URISIRE                  1025
#define IDC_ST_DCBR                     1026
#define IDC_ST_CBMN                     1027
#define IDC_ST_DKJ                      1028
#define IDC_ST_CKJ                      1029
#define IDC_ST_SKBN                     1030
#define IDC_STATIC1                     1031
#define IDC_ST_SNUM                     1032
#define IDC_STATIC15                    1033
#define IDC_STATIC2                     1034
#define IDC_ST_TDAT                     1035
#define IDC_STATIC16                    1036
#define IDC_ST_SEQ                      1037
#define IDC_STATIC17                    1038
#define IDC_ST_DATE                     1039
#define IDC_ST_DENP                     1040
#define IDC_STATIC6                     1041
#define IDC_ST_DBMN                     1042
#define IDC_STATIC18                    1042
#define IDC_ST_ZRITU                    1043
#define IDC_STATIC20                    1043
#define IDC_ST_ORDER                    1044
#define IDC_STATIC7                     1045
#define IDC_STATIC11                    1046
#define IDC_STATIC12                    1047
#define IDC_STATIC13                    1048
#define IDC_STATIC14                    1049
#define IDC_STATIC_BOX1                 1050
#define IDC_STATIC_BOX2                 1051
#define IDC_STATIC_BOX3                 1052
#define IDC_ST_DUSER                    1053
#define IDC_ST_HUSEN                    1054
#define IDC_ST_SEARCHTYPE               1055
#define IDC_ST_STYPE                    1056
#define IDC_ICSSELCTRL1                 1057
#define IDC_ST_NOIPBRN                  1058
#define IDC_ICSSELCTRL2                 1059
#define IDC_ICSDBEDTNAME                1060
#define IDC_LIST1                       1061
#define IDC_SCNSEQ1                     1062
#define IDC_SCNSEQ2                     1063
#define IDC_SCNDATE1                    1064
#define IDC_ICSLISTINPCTRL1             1065
#define IDC_HOMEBUTTON                  1066
#define IDC_SCNDATE2                    1067
#define IDC_RIGHTBUTTON                 1068
#define IDC_SCNDENP1                    1069
#define IDC_LEFTBUTTON                  1070
#define IDC_SCNDENP2                    1071
#define IDC_LEFTBUTTON2                 1072
#define IDC_SUBBUTTON                   1073
#define IDC_SCNBMON1                    1074
#define IDC_ADDBUTTON                   1075
#define IDC_SCNBMON2                    1076
#define IDC_SCNCBMN1                    1077
#define IDC_STATIC3                     1078
#define IDC_SCNCBMN2                    1079
#define IDC_STATIC_EDNAM                1080
#define IDC_BUTTON_TOROK                1081
#define IDC_SCNKOJI1                    1082
#define IDC_RADIO_DEBT                  1083
#define IDC_SCNKOJI2                    1084
#define IDC_RADIO_CRED                  1085
#define IDC_ICSDISPCTRL1                1086
#define IDC_SCNCKJI1                    1087
#define IDC_SCNDEBT                     1088
#define IDC_SCNDBR1                     1089
#define IDC_SCNDBR2                     1090
#define IDC_SCNCRED                     1091
#define IDC_SPIN1                       1092
#define IDC_VALTITLE                    1093
#define IDC_SCNCBR1                     1094
#define IDC_HUSEN1                      1095
#define IDC_HUSEN2                      1096
#define IDC_HUSEN3                      1097
#define IDC_HUSEN4                      1098
#define IDC_HUSEN5                      1099
#define IDC_HUSEN6                      1100
#define IDC_HUSEN7                      1101
#define IDC_STATIC_FRM                  1102
#define IDC_VALTITLEBASE                1103
#define IDC_SCNCBR2                     1104
#define IDC_STATIC_FRM3                 1105
#define IDC_STATIC_PT                   1106
#define IDC_STATIC_FRM4                 1107
#define IDC_SCNDBCR                     1108
#define IDC_SCNDCBR1                    1109
#define IDC_SCNDCBR2                    1110
#define IDC_SCNVAL1                     1111
#define IDC_BUTTON_CHG                  1112
#define IDC_SCNVAL2                     1113
#define IDC_SCNZEI1                     1114
#define IDC_SCNZEI2                     1115
#define IDC_SCNTKY                      1116
#define IDC_LISTTKSRCH                  1117
#define IDC_SCNSNUM1                    1118
#define IDC_SCNSNUM2                    1119
#define IDC_SCNTDAT1                    1120
#define IDC_SCNTDAT2                    1121
#define IDC_SCNCKJI2                    1122
#define IDC_NCHK_SEQ                    1123
#define IDC_NCHK_DATE                   1124
#define IDC_SCNSYZSW                    1125
#define IDC_STATIC_WAKU                 1126
#define IDC_SCNSKBN                     1127
#define IDC_ICSDIAG8CTRL1               1128
#define IDC_ICSDIAG8CTRL2               1129
#define IDC_SCNURISIRE                  1130
#define IDC_SCNZRITU                    1131
#define IDC_STATIC_ARROW                1132
#define IDC_SCNHUSEN                    1133
#define IDC_ICSDISP8CTRL1               1134
#define IDC_BUTTON_COPY                 1135
#define IDC_SCNNOINPBRN                 1136
#define IDC_NCHK_DENP                   1137
#define IDC_NCHK_DBMN                   1138
#define IDC_NCHK_CBMN                   1139
#define IDC_NCHK_SYKBN                  1140
#define IDC_NCHK_SYZSW                  1141
#define IDC_LIST_KMNAM                  1142
#define IDC_NCHK_ZKBN                   1143
#define IDC_NCHK_SKBN                   1144
#define IDC_STATIC_KMNAM                1145
#define IDC_ADD                         1146
#define IDC_NCHK_ZRITU                  1147
#define IDC_REP                         1148
#define IDC_NCHK_URISIRE                1149
#define IDC_STATIC_KMKDSP               1150
#define IDC_TOROK                       1151
#define IDC_NCHK_SNUMBER                1152
#define IDC_NCHK_SNUM                   1153
#define IDC_NCHK_TGDATE                 1154
#define IDC_ICSDISPJOB                  1155
#define IDC_BUTTON_DEBKMK               1156
#define IDC_NCHK_HUSEN                  1157
#define IDC_BUTTON_CREKMK               1158
#define IDC_NCHK_VAL                    1159
#define IDC_BUTTON_SWK                  1160
#define IDC_NCHK_ZEI                    1161
#define IDC_BUTTON_DEBCRE               1162
#define IDC_IMAGE1                      1163
#define IDC_IMAGE2                      1164
#define IDC_IMAGE3                      1165
#define IDC_IMAGE4                      1166
#define IDC_IMAGE5                      1167
#define IDC_IMAGE6                      1168
#define IDC_IMAGE7                      1169
#define IDC_IMAGE8                      1170
#define IDC_NCHK_DBT                    1171
#define IDC_STATIC_DT                   1172
#define IDC_NCHK_CRE                    1173
#define IDC_EDIT1                       1174
#define IDC_NCHK_DBCR                   1175
#define IDC_STATIC_CT                   1176
#define IDC_TKYCOMBO                    1177
#define IDC_STATIC_IDGUID               1178
#define IDC_DISPETC                     1179
#define IDC_ICSDISPBKMK                 1180
#define IDC_IMGTKYEDIT                  1181
#define IDC_CHECK_DBR                   1182
#define IDC_CHECK_DBM                   1183
#define IDC_CHECK_CBR                   1184
#define IDC_CHECK_CBM                   1185
#define IDC_CHECK_DKJ                   1186
#define IDC_CHECK_CKJ                   1187
#define IDC_NCHK_DBRN                   1188
#define IDC_NCHK_CBRN                   1189
#define IDC_NCHK_DCBRN                  1190
#define IDC_NCHK_DKJI                   1191
#define IDC_NCHK_CKJI                   1192
#define IDC_COMBO3                      1193
#define IDC_COMBO_STYPE                 1194
#define IDC_RADIO1                      1195
#define IDC_RADIO2                      1196
#define IDC_MNTHSEL                     1197
#define IDC_RADIO3                      1198
#define IDC_RADIO4                      1199
#define IDC_SELGUIDE                    1200
#define IDC_RADIO5                      1201
#define IDC_STATIC0                     1202
#define IDC_RADIO6                      1203
#define IDC_ICSDISPCTRL2                1204
#define IDC_TKYONLY                     1205
#define IDC_DISPORDER                   1206
#define IDC_STATIC_KM                   1207
#define IDC_ALLKEYDEL                   1208
#define IDC_DATA_USER                   1209
#define IDC_STATIC_EDA                  1210
#define IDC_STATIC_TKCD                 1211
#define IDC_STATIC_EDANAM               1212
#define IDC_STATIC_EDAZAN               1213
#define IDC_STD_KNAM                    1214
#define IDC_STD_EDA                     1215
#define IDC_STD_EDNAM                   1216
#define IDC_STATIC_GUID                 1217
#define IDC_STATIC_EDANAM2              1218
#define IDC_STATIC_KANA                 1219
#define IDC_STATIC_GD                   1220
#define IDC_STATIC_BMN                  1221
#define IDC_STD_BMNAM                   1222
#define IDC_ICSDBEDTCTRL1               1223
#define IDC_ICSDBEDTCTRL2               1224
#define IDC_ICSDBEDTCTRL3               1225
#define IDC_ICSDBEDTCTRL4               1226
#define IDC_ICSDBEDTCTRL5               1227
#define IDC_STATIC_KEZAN                1228
#define IDC_ICSDBEDTCTRL6               1229
#define IDC_ICSDBEDTCTRL7               1230
#define IDC_ICSDBEDTCTRL_INVOICE        1230
#define IDC_ICSDBEDT_INVOICE            1230
#define IDC_ICSDBEDT_INV                1230
#define IDC_ICSDBEDT_TOKU               1231
#define IDC_ICSDBEDT_INV2               1231
#define IDC_ICSDBEDT_MEN                1232
#define IDC_ICSDBEDT_INV3               1233
#define IDC_ICSDBEDT_INVDISP            1233
#define IDC_HS_COMBO                    1234
#define IDC_FURIBUTTON                  1235
#define IDC_ICSDBEDT_KASITKY            1300
#define IDC_ICSDBEDT_KOJI               1301
#define IDC_ICSDBEDT_TGNUM              1302
#define IDC_ICSDBEDT_BMON               1303
#define IDC_ICSDBEDT_SYOBRN             1304
#define IDC_ICSDBEDT_SYONUM             1305
#define IDC_ICSDBEDT8CTRL1              1306
#define IDC_ICSDBEDT_KMINP              1307
#define IDC_ICSDBEDT_KMINP2             1308
#define IDC_ST_TYPE                     1519
#define IDC_SCROLLBAR1                  1569
#define IDC_ICSLINP8_SWK                5001
#define IDC_ICSLINP8_TKY                5002
#define IDD_HJIYU_DLG                   5004
#define IDD_DLG_IND                     5005
#define IDD_DLG_PUBK                    5006
#define IDC_BTN_END                     5007
#define IDD_TKYV2_DLG                   5007
#define IDC_BTN_F8                      5008
#define IDD_DLG_TKYEDA                  5008
#define IDC_BTN_F9                      5009
#define IDC_ICSDBEDT_KEZAN              5009
#define IDD_DLG_TKYSEL                  5009
#define IDC_EDIT2                       5010
#define IDC_EDIT                        5010
#define IDC_BTN_F3                      5010
#define IDC_COMBO1                      5011
#define IDC_COMBO_JIGYO                 5011
#define IDD_TKSWK_CPY                   5011
#define IDC_COMBO_MEN                   5011
#define IDC_CHECK1                      5012
#define IDC_COMBO_KANRI                 5012
#define IDC_ICSDBEDT8_TKY               5012
#define IDC_CHECK2                      5013
#define IDC_ICSDBEDT8_KANA              5013
#define IDC_CHK_TKYREG                  5013
#define IDC_CHECK3                      5014
#define IDC_CHK_KMKDEB                  5014
#define IDR_TOOLBAR1                    5014
#define IDC_CHECK4                      5015
#define IDC_CHK_KMKCRE                  5015
#define IDC_CHK_SWKTKY                  5016
#define IDD_DLG_DELTKY                  5016
#define IDC_CHK_TANDEB                  5017
#define IDD_SYKBNLITE_DLG               5017
#define IDC_CHK_TANCRE                  5018
#define IDC_STATIC_FRM2                 5019
#define IDC_STATIC_G1                   5020
#define IDC_STATIC_G2                   5021
#define IDC_STATIC_G3                   5022
#define IDC_STATIC_G4                   5023
#define IDC_STATIC_G5                   5024
#define IDC_CHK_TKYONLY                 5025
#define IDC_STATIC_G6                   5026
#define IDC_CHK_BRNDEB                  5027
#define IDC_CHK_BRNCRE                  5028
#define IDC_STATIC_G7                   5029
#define IDC_STATIC_G8                   5030
#define IDC_BRNDEB_BTN                  5031
#define IDC_ICSLINP8CTRL1               5032
#define IDC_BRNCRE_BTN                  5032
#define IDC_STATIC_KMK                  5033
#define IDC_ICSDBEDT8_DZBRN             5033
#define IDC_BUTTON1                     5034
#define IDC_BTN_TKYSEL                  5034
#define IDC_ICSDBEDT8CTRL2              5035
#define IDC_BUTTON2                     5035
#define IDC_STATIC_GNUM                 5035
#define IDC_STATIC_TKCOD                5036
#define IDC_ICSDBEDT8_CZBRN             5036
#define IDC_STATIC_GRP                  5036
#define IDC_STATIC_TKNUM                5037
#define IDC_STATIC_TXT                  5037
#define IDC_CUSTOM1                     5038
#define IDC_ICON_STATIC                 5039
#define IDC_STATIC_TXT2                 5040
#define IDC_REPORT_TKDIC                5040
#define IDC_STATIC19                    5040
#define IDC_CHECK_MENZEI                5041
#define ID_TLBAR_F1                     32701
#define ID_TLBAR_F2                     32702
#define ID_TLBAR_F3                     32703
#define ID_TLBAR_F4                     32704
#define ID_TLBAR_F5                     32705
#define ID_TLBAR_F6                     32706
#define ID_TLBAR_F7                     32707
#define ID_TLBAR_F8                     32708
#define ID_TLBAR_F9                     32709
#define ID_TLBAR_F11                    32710
#define ID_TLBAR_F12                    32711
#define ID_TLBAR_INS                    32712
#define ID_TLBAR_DEL                    32713
#define ID_TLBAR_END                    32714
#define ID_TLBAR_ESC                    32715
#define ID_BUTTON_F1                    32773
#define ID_BUTTON_F2                    32774
#define ID_BUTTON_F3                    32775
#define ID_BUTTON_F4                    32776
#define ID_BUTTON_F6                    32778
#define ID_BUTTON_F7                    32779
#define ID_BUTTON_F8                    32780
#define ID_BUTTON_F9                    32781
#define ID_BUTTON_F11                   32782
#define ID_BUTTON_F12                   32783
#define ID_BUTTON_END                   32784
#define IDM_LINE_COPY                   32804
#define IDM_LINE_PASTE                  32805
#define IDM_LINE_DELETE                 32818
#define ID_BUTTON_COSEL                 50002
#define ID_BUTTON_F5                    57607

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        5019
#define _APS_NEXT_COMMAND_VALUE         32778
#define _APS_NEXT_CONTROL_VALUE         5042
#define _APS_NEXT_SYMED_VALUE           5000
#endif
#endif
