//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DBDinp.rc
//
#define IDR_MANIFEST                    1
#define IDC_SWKDEL                      3
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             101
#define IDD_DBDINP_FORM                 102
#define IDD_DNPBASEDLG                  103
#define ID_KENGYOMODE                   104
#define IDR_MAINFRAME                   128
#define IDR_DBDINPTYPE                  129
#define ID_VIEW_THEME_OFFICEXP          130
#define IDC_ACTIVATE                    131
#define IDC_CLOSEDOCUMENT               132
#define IDC_HIDETABS                    133
#define IDR_TAB_POPUP                   134
#define IDC_ALIGNTABTOP                 135
#define IDC_ALIGNTABBOTTOM              136
#define IDC_ALIGNTABLEFT                137
#define IDC_ALIGNTABRIGHT               138
#define IDR_SKEYFRAME                   139
#define IDD_DLG_FURI                    140
#define IDD_DBBASEVIEW                  141
#define IDD_DNPSELDLG                   142
#define IDB_SKINBITMAP                  143
#define IDR_SCANFRAME                   144
#define IDR_ACBKFRAME                   145
#define IDD_DLG_ACSEL                   146
#define IDB_FURIBITMAP                  147
#define IDD_SYKBN_DLG                   148
#define IDB_NKINBITMAP                  149
#define IDD_TTLDSP                      150
#define IDD_AUTOINP                     151
#define IDD_ENVDIALOG                   152
#define IDR_ACCELERATOR1                153
#define IDB_HUSEN_BMP                   154
#define IDD_TAIDSP                      155
#define IDD_DSPOPT_DLG                  156
#define IDD_BKINP_DLG                   157
#define IDD_DKEY_DLG                    158
#define IDD_MNTH_DLG                    159
#define IDD_HUSEN_DLG                   160
#define IDB_HSBITMAP                    161
#define IDD_SUBDATA_DLG                 162
#define IDD_DLGSIWAKE                   163
#define IDD_MSG_DLG                     164
#define IDD_RDSEL                       165
#define IDD_SELIMG_DLG                  166
#define IDD_SCANKEYFORM                 167
#define IDD_DBABOOK_FORM                168
#define IDD_DBDNPINVIEW                 169
#define IDD_DLG_NSKIN                   170
#define IDD_DLG_DELSWK                  171
#define IDD_DBDINP_FORM1                172
#define IDD_DBABOOK_FORM1               173
#define IDD_DLG_RDREG                   174
#define IDI_ICON_ATTACH                 175
#define IDD_DLG_RDGRPADD                176
#define IDI_ICON_ATTACHED               177
#define IDD_SCAN_FORM                   178
#define IDI_ICON_DISPSLIP               179
#define IDD_ACDSPOPT_DLG                180
#define IDI_ICON_PLUR                   181
#define IDI_ICON_PLURAL_ATTACH          182
#define IDD_DLG_DCOPY                   183
#define IDR_SWKMENU                     184
#define IDD_ACINPSUP_DLG                185
#define IDD_DLG_SELWND                  186
#define IDC_ACBOOKLIST                  1000
#define IDC_ALLKEYDEL                   1001
#define IDC_ALT                         1002
#define IDC_BILLINP                     1003
#define IDC_BMN_CHECK                   1004
#define IDC_BMNBRN_REG                  1005
#define IDC_BMNTKBR_CHK                 1006
#define IDC_BMNFIX                      1007
#define IDC_BMNINP_CHK                  1008
#define IDC_BMNNAM_DSP                  1009
#define IDC_BMNSELGRP                   1010
#define IDC_BRN_CPY                     1011
#define IDC_BRN_INPCHK                  1012
#define IDC_BRNNAM_DSP                  1013
#define IDC_BRNTOSWK                    1014
#define IDC_BRNUM                       1015
#define IDC_KJI_INPCHK                  1016
#define IDC_KOJITOSWK                   1017
#define IDC_BRNUMTITLE                  1018
#define IDC_KANKJI_CHK                  1019
#define IDC_BS_CHK                      1020
#define IDC_BSTOTAL                     1021
#define IDC_KJIKMK_CHK                  1022
#define IDC_BSTOTAL_CRE                 1023
#define IDC_BRN_INPCHK2                 1024
#define IDC_BRN_INPKAKU                 1025
#define IDC_BSTOTAL_DEB                 1026
#define IDC_BSTOTALTITLE                1027
#define IDC_BSTOTALTITLE2               1028
#define IDC_BTN_DEL                     1029
#define IDC_BTN_END                     1030
#define IDC_BTN_IKATU                   1031
#define IDC_BTN_NOMDFY                  1032
#define IDC_BTN_OK                      1033
#define IDC_BUTTON_DISP                 1034
#define IDC_BUTTON1                     1035
#define IDC_BUTTON2                     1036
#define IDC_BUTTON3                     1037
#define IDC_BUTTON4                     1038
#define IDC_CHECK_CBM                   1039
#define IDC_CHECK_CBR                   1040
#define IDC_CHECK_CBR2                  1041
#define IDC_CHECK_CKJ                   1042
#define IDC_CHECK_DBM                   1043
#define IDC_CHECK_DBM2                  1044
#define IDC_CHECK_TKY                   1045
#define IDC_CHECK_DBR                   1046
#define IDC_CHECK_DENP                  1047
#define IDC_CHECK_DKJ                   1048
#define IDC_CHECK1                      1049
#define IDC_CHECK_KMSYZ                 1050
#define IDC_CHECK_DENP2                 1051
#define IDC_CHECK_SNO                   1052
#define IDC_CHECK_MNONLY                1053
#define IDC_SELDSP_CHK                  1054
#define IDC_COMBO_STYPE                 1055
#define IDC_CHK_CONFIRM                 1057
#define IDC_CHECK2                      1058
#define IDC_CHECK3                      1059
#define IDC_CHK_HUSEN                   1061
#define IDC_COMBO1                      1062
#define IDC_TKY_REPORT                  1063
#define IDC_CREDFIX                     1064
#define IDC_DATA_USER                   1065
#define IDC_CUSTOM1                     1066
#define IDC_DATANUM                     1067
#define IDC_DATANUMTITLE                1068
#define IDC_DATE_SEL                    1069
#define IDC_DATEFIX                     1070
#define IDC_DEBTFIX                     1071
#define IDC_DEBTOTALTITLE               1072
#define IDC_DEL_SWK                     1073
#define IDC_DENP_COMBO                  1074
#define IDC_DISPETC                     1075
#define IDC_DENPMODEGRP                 1076
#define IDC_DISPORDER                   1077
#define IDC_DISPBIGIMG                  1078
#define IDC_DENP_COMBO2                 1079
#define IDC_SNO_COMBO                   1080
#define IDC_SNO_GRP                     1081
#define IDC_DSP_CRED                    1082
#define IDC_FURI_CHK                    1083
#define IDC_DSP_CRED2                   1084
#define IDC_DSP_DEBT                    1085
#define IDC_DTLIST                      1086
#define IDC_DTLINE                      1087
#define IDC_FIXDATEGRP                  1088
#define IDC_HJIYUTOSWK                  1089
#define IDC_HS_COMBO                    1090
#define IDC_HUSEN1                      1091
#define IDC_HUSEN2                      1092
#define IDC_HUSEN3                      1093
#define IDC_HUSEN4                      1094
#define IDC_HUSEN5                      1095
#define IDC_HUSEN6                      1096
#define IDC_HUSEN7                      1097
#define IDC_HUSENINP                    1098
#define IDC_ICSDBEDT_BMN                1099
#define IDC_ICSDBEDT_BSKMK              1100
#define IDC_ICSDBEDT_BMON               1101
#define IDC_ICSDBEDT_DATE               1102
#define IDC_ICSDBEDT_KMK                1103
#define IDC_ICSDBEDT_KASITKY            1104
#define IDC_ICSDBEDT_KOJI               1105
#define IDC_ICSDBEDT_TGNUM              1106
#define IDC_ICSDBEDT8CTRL1              1107
#define IDC_ICSDBEDTCTRL1               1108
#define IDC_ICSDBEDTCTRL2               1109
#define IDC_ICSDBEDT8CTRL3              1110
#define IDC_ICSDBEDTCTRL3               1111
#define IDC_ICSDBEDTCTRL4               1112
#define IDC_ICSDBEDTCTRL5               1113
#define IDC_ICSDIAG8CTRL1               1114
#define IDC_ICSDIAG8CTRL2               1115
#define IDC_ICSDIAG8CTRL3               1116
#define IDC_ICSDISP_SELIMG              1117
#define IDC_ICSDISP_SEQ                 1118
#define IDC_ICSDISP8CTRL1               1119
#define IDC_ICSDISPCTRL1                1120
#define IDC_ICSDISP8CTRL2               1121
#define IDC_ICSDISPCTRL2                1122
#define IDC_ICSDISPCTRL10               1123
#define IDC_ICSDISP8CTRL3               1124
#define IDC_ICSDISPCTRL11               1125
#define IDC_ICSDISPCTRL12               1126
#define IDC_ICSDISPCTRL3                1127
#define IDC_ICSDISPCTRL4                1128
#define IDC_ICSDISPCTRL5                1129
#define IDC_ICSDISPCTRL6                1130
#define IDC_ICSDISPCTRL7                1131
#define IDC_ICSDISPCTRL8                1132
#define IDC_ICSDISPCTRL9                1133
#define IDC_ICSDISPGENKIN               1134
#define IDC_ICSDISPJOB                  1135
#define IDC_ICSDISPRDREMAIN             1136
#define IDC_ICSDISPSYOGT                1137
#define IDC_ICSLISTINPCTRL1             1138
#define IDC_ICSSELCTRL1                 1139
#define IDC_ICSSELCTRL2                 1140
#define IDC_ICSSELCTRL3                 1141
#define IDC_IMAGE1                      1142
#define IDC_IMAGE2                      1143
#define IDC_IMAGE3                      1144
#define IDC_IMAGE4                      1145
#define IDC_IMAGE5                      1146
#define IDC_IMAGE6                      1147
#define IDC_IMAGE7                      1148
#define IDC_IMAGE8                      1149
#define IDC_ICSDISPBKMK                 1150
#define IDC_IMPORT_CHK                  1151
#define IDC_KANADISP_CHK                1152
#define IDC_KARITOTAL                   1153
#define IDC_ZEIMDFY_CHK                 1154
#define IDC_KASITOTAL                   1155
#define IDC_DELSWK_CHK                  1156
#define IDC_KM_COMBO                    1157
#define IDC_SCNCLR_CHK                  1158
#define IDC_KMKSELGRP                   1159
#define IDC_KMKSELGRP1                  1160
#define IDC_KMKSELGRP2                  1161
#define IDC_KOJIFIX                     1162
#define IDC_TKYSELGRP                   1163
#define IDC_MNTHSEL                     1164
#define IDC_MOTO_SWK                    1165
#define IDC_SELGUIDE                    1166
#define IDC_NCHK_SNUM                   1167
#define IDC_NCHK_SNO                    1168
#define IDC_NCHK_SYKBN                  1169
#define IDC_NCHK_VAL2                   1170
#define IDC_NCHK_URISIRE2               1171
#define IDC_NCHK_ZKBN                   1172
#define IDC_NEW_SWK                     1173
#define IDC_NORMALTOTAL                 1174
#define IDC_NORMALTOTAL_CRE             1175
#define IDC_NORMALTOTAL_DEB             1176
#define IDC_NORMALTOTALTITLE            1177
#define IDC_OTHER_GRP                   1178
#define IDC_RADIO_SW1                   1179
#define IDC_SYZ_GRP                     1180
#define IDC_RADIO_SW2                   1181
#define IDC_RADIO1                      1182
#define IDC_RADIO2                      1183
#define IDC_IMGTKYEDIT                  1184
#define IDC_RADIO_SKN1                  1185
#define IDC_RADIOBMNSELYES              1186
#define IDC_RADIO4                      1187
#define IDC_RADIO_SKN2                  1188
#define IDC_RADIOBMNSELNO               1189
#define IDC_RADIOKMCODE                 1190
#define IDC_RADIOKMNUM                  1191
#define IDC_RADIOKMKEEP                 1192
#define IDC_RADIOKMTOP                  1193
#define IDC_RADIOSWKTEKYES              1194
#define IDC_RADIOSWKTEKNO               1195
#define IDC_RD_BMNNO                    1196
#define IDC_RADIOSWKTKY1                1197
#define IDC_RD_BMNYES                   1198
#define IDC_RADIOSWKTKY2                1199
#define IDC_RD_BRN                      1200
#define IDC_RD_DATE                     1201
#define IDC_RD_DENPNO                   1202
#define IDC_RD_DENPYES                  1203
#define IDC_NCHK_CBMN                   1204
#define IDC_RD_KOJINO                   1205
#define IDC_NCHK_CBRN                   1206
#define IDC_RD_KOJIYES                  1207
#define IDC_NCHK_CKJI                   1208
#define IDC_RD_LNHT1                    1209
#define IDC_NCHK_CRE                    1210
#define IDC_CHK_TKYTYPE2                1211
#define IDC_NCHK_DATE                   1212
#define IDC_RD_LNHT2                    1213
#define IDC_NCHK_DBCR                   1214
#define IDC_RD_SYONO                    1215
#define IDC_NCHK_DBMN                   1216
#define IDC_CHK_VALNOT                  1217
#define IDC_NCHK_DBRN                   1218
#define IDC_RD_SYOYES                   1219
#define IDC_NCHK_DBT                    1220
#define IDC_CHK_ZMVDATE                 1221
#define IDC_NCHK_DCBRN                  1222
#define IDC_RD_TGDTNO                   1223
#define IDC_NCHK_DENP                   1224
#define IDC_RD_TGDTYES                  1225
#define IDC_NCHK_DKJI                   1226
#define IDC_RDLBL_CMBO                  1227
#define IDC_NCHK_HUSEN                  1228
#define IDC_RD_HJIYUYES                 1229
#define IDC_NCHK_SEQ                    1230
#define IDC_RDLIST                      1231
#define IDC_NCHK_SKBN                   1232
#define IDC_RD_HJIYUNO                  1233
#define IDC_NCHK_DCBMN                  1234
#define IDC_RGDATA_GRP                  1235
#define IDC_NCHK_TKY                    1236
#define IDC_SCANLIST                    1237
#define IDC_NCHK_SNUMBER                1238
#define IDC_NCHK_DCKJI                  1239
#define IDC_NCHK_SYZSW                  1240
#define IDC_NCHK_TAI                    1241
#define IDC_NCHK_TGDATE                 1242
#define IDC_NCHK_URISIRE                1243
#define IDC_VALCPY_GRP                  1244
#define IDC_NCHK_VAL                    1245
#define IDC_TKYREG_GRP                  1246
#define IDC_ZMOVE_GRP                   1247
#define IDC_NCHK_TOKUS                  1248
#define IDC_NCHK_ZEI                    1249
#define IDC_NCHK_ZRITU                  1250
#define IDC_NYUK_CHK                    1251
#define IDC_SCNSEQ1                     1300
#define IDC_SCNSEQ2                     1301
#define IDC_SCNDATE1                    1302
#define IDC_SCNDATE2                    1303
#define IDC_SCNBMON1                    1304
#define IDC_SCNBMON2                    1305
#define IDC_SCNCBMN1                    1306
#define IDC_SCNCBMN2                    1307
#define IDC_SCNDCBMN1                   1308
#define IDC_SCNDCBMN2                   1309
#define IDC_SCNKOJI1                    1310
#define IDC_SCNKOJI2                    1311
#define IDC_SCNCKJI1                    1312
#define IDC_SCNCKJI2                    1313
#define IDC_SCNDCKJI1                   1314
#define IDC_SCNDCKJI2                   1315
#define IDC_SCNDEBT                     1316
#define IDC_SCNDEBT2                    1317
#define IDC_SCNCRED                     1318
#define IDC_SCNCRED2                    1319
#define IDC_SCNDENP1                    1320
#define IDC_SCNDENP2                    1321
#define IDC_SCNVAL1                     1322
#define IDC_SCNVAL2                     1323
#define IDC_SCNTKY                      1324
#define IDC_SCNTKY2                     1325
#define IDC_SCNSNUM1                    1326
#define IDC_SCNSNUM2                    1327
#define IDC_SCNSNO1                     1328
#define IDC_SCNSNO2                     1329
#define IDC_SCNTDAT1                    1330
#define IDC_SCNTDAT2                    1331
#define IDC_SCNDBR1                     1332
#define IDC_SCNDBR2                     1333
#define IDC_SCNCBR1                     1334
#define IDC_SCNCBR2                     1335
#define IDC_SCNDCBR1                    1336
#define IDC_SCNDCBR                     1336
#define IDC_SCNDCBR2                    1337
#define IDC_SCNDBCR                     1338
#define IDC_SCNDBCR2                    1339
#define IDC_SCNZEI1                     1340
#define IDC_SCNZEI2                     1341
#define IDC_SCNTAIKA1                   1342
#define IDC_SCNTAIKA2                   1343
#define IDC_SCNHUCMT                    1344
#define IDC_SCNHUSEN                    1400
#define IDC_SCNHUSEN2                   1401
#define IDC_SCNHJIYU                    1402
#define IDC_SCNHJIYU2                   1403
#define IDC_SCNSKBN                     1404
#define IDC_SCNSKBN2                    1405
#define IDC_SCNSYZSW                    1406
#define IDC_SCNSYZSW2                   1407
#define IDC_SCNTOKUS                    1408
#define IDC_SCNTOKUS2                   1409
#define IDC_SCNURISIRE                  1410
#define IDC_SCNURISIRE2                 1411
#define IDC_SCNZRITU                    1412
#define IDC_SCNZRITU2                   1413
#define IDC_SCN_DATESEL                 1414
#define IDC_SPIN1                       1415
#define IDC_SPIN2                       1416
#define IDC_TKYTAB_GRP                  1417
#define IDC_ST_BMN                      1418
#define IDC_ST_BMNGRP                   1419
#define IDC_ST_BRNGRP                   1420
#define IDC_ST_CBMN                     1421
#define IDC_ST_CKJ                      1422
#define IDC_ST_CRED                     1423
#define IDC_ST_DATE                     1424
#define IDC_ST_DBMN                     1425
#define IDC_ST_DBMN2                    1426
#define IDC_ST_DEBT                     1427
#define IDC_ST_DENP                     1428
#define IDC_ST_DKJ                      1429
#define IDC_ST_TKBRNGRP                 1430
#define IDC_ST_FIXGRP                   1431
#define IDC_ST_SNO                      1432
#define IDC_ST_HJIYU                    1433
#define IDC_ST_HUSEN                    1434
#define IDC_ST_KOJI                     1435
#define IDC_ST_LNHT                     1436
#define IDC_ST_SKBN                     1437
#define IDC_ST_SNUM                     1438
#define IDC_ST_SWKSEL                   1439
#define IDC_ST_SYONO                    1440
#define IDC_ST_SYZSW                    1441
#define IDC_ST_BLKMOVE                  1442
#define IDC_ST_GRP                      1443
#define IDC_ST_TDAT                     1444
#define IDC_ST_SNO2                     1445
#define IDC_ST_DATA                     1446
#define IDC_ST_TGDT                     1447
#define IDC_ST_GRPCNT                   1448
#define IDC_ST_TKYTAB                   1449
#define IDC_ST_DATACNT                  1450
#define IDC_ST_CONFIRM                  1451
#define IDC_ST_TKY                      1452
#define IDC_ST_URISIRE                  1453
#define IDC_ST_VAL                      1454
#define IDC_ST_ZEI                      1455
#define IDC_ST_URISIRE2                 1456
#define IDC_ST_ZRITU                    1457
#define IDC_STATIC_KARA                 1458
#define IDC_ST_TOKUS                    1459
#define IDC_STATIC_MSG                  1460
#define IDC_STATIC_POS                  1461
#define IDC_STATIC_POS2                 1462
#define IDC_STATIC_WAK                  1463
#define IDC_STATIC_WAK2                 1464
#define IDC_STATIC_WAK3                 1465
#define IDC_STATIC_WAK4                 1466
#define IDC_STATIC_WAK5                 1467
#define IDC_STATIC_WAK6                 1468
#define IDC_STATIC_WAK7                 1469
#define IDC_STATIC_WAK8                 1470
#define IDC_STATIC1                     1471
#define IDC_STATIC_WAK10                1472
#define IDC_STATIC24                    1473
#define IDC_STATIC_WAK9                 1474
#define IDC_STATIC11                    1475
#define IDC_STATIC12                    1476
#define IDC_STATIC13                    1477
#define IDC_STATIC14                    1478
#define IDC_STATIC15                    1479
#define IDC_STATIC16                    1480
#define IDC_STATIC17                    1481
#define IDC_STATIC18                    1482
#define IDC_STATIC19                    1483
#define IDC_STATIC2                     1484
#define IDC_STATIC20                    1485
#define IDC_STATIC21                    1486
#define IDC_STATIC3                     1487
#define IDC_STATIC4                     1488
#define IDC_STATIC5                     1489
#define IDC_STATIC6                     1490
#define IDC_STATIC7                     1491
#define IDC_ST_TYPE                     1492
#define IDC_STATIC26                    1493
#define IDC_STATIC_TKY1                 1494
#define IDC_STATIC27                    1495
#define IDC_BTN_INIT                    1496
#define IDC_STATIC_TKY2                 1497
#define IDC_STATIC_TKYGD                1498
#define IDC_SWKTEKGRP                   1499
#define IDC_SWKTEKGRP2                  1500
#define IDC_SYO_BUZZER                  1501
#define IDC_SYOBRN_DSP                  1502
#define IDC_SCNNOINPBRN                 1503
#define IDC_SYOG_SAGAK                  1504
#define IDC_CHK_VALCOPY                 1505
#define IDC_SYO_BUZZER2                 1506
#define IDC_STATIC_LINE                 1507
#define IDC_SCNGYOKBN                   1508
#define IDC_SCAN_KMCD                   1509
#define IDC_SYOGBS                      1510
#define IDC_CHK_TKYTYPE1                1511
#define IDC_SYOGBSTITLE                 1512
#define IDC_CHK_TKYTYPE3                1513
#define IDC_ST_CBR                      1514
#define IDC_SYOGTOTAL                   1515
#define IDC_CHK_ZMVZANC                 1516
#define IDC_SYOGTOTAL_CRE               1517
#define IDC_SWTKYDGRP                   1518
#define IDC_ST_DBCR                     1519
#define IDC_SYOGTOTAL_DEB               1520
#define IDC_SYOGTOTALTITLE              1521
#define IDC_ST_DBR                      1522
#define IDC_ST_DCBMN                    1523
#define IDC_ST_DCBR                     1524
#define IDC_VALTITLE                    1525
#define IDC_VALTITLEBASE                1526
#define IDC_WANING                      1527
#define IDC_ST_DENP2                    1528
#define IDC_WANING2                     1529
#define IDC_CHK_CONMDFY                 1530
#define IDC_ST_DUSER                    1531
#define IDC_ICSDBEDT_TGDATE             1532
#define IDC_ICSDBEDT_TGNO               1533
#define IDC_ST_DCKJ                     1534
#define IDC_ICSDBEDT_HUSEN              1535
#define IDC_RD_ZEIYES                   1536
#define IDC_RD_ZEINO                    1537
#define IDC_STATIC22                    1538
#define IDC_STATIC_GRP                  1539
#define IDC_CHK_TKYTAB                  1540
#define IDC_NOWDATA                     1541
#define IDC_ST_NOIPBRN                  1542
#define IDC_RD_VALCHK                   1543
#define IDC_ST_ORDER                    1544
#define IDC_SCROLLBAR1                  1545
#define IDC_ST_SEQ                      1546
#define IDC_BTN_GRPADD                  1547
#define IDC_DISPSLIP_CHK                1548
#define IDC_PROGRESS_RECCNT             1549
#define IDC_ST_STYPE                    1550
#define IDC_LINKSLIP_BTN                1551
#define IDC_STATIC_MESSAGE_1            1552
#define IDC_DISPSLIP_BTN                1553
#define IDC_ST_TAIKA                    1554
#define IDC_STATIC23                    1555
#define IDC_RD_DISPDATE                 1556
#define IDC_RD_DISPSEQ                  1557
#define IDC_ST_GYOKBN                   1558
#define IDC_RD_NOFIX                    1559
#define IDC_RD_SKINFIX                  1560
#define IDC_RD_NKINFIX                  1561
#define IDC_STATIC_GUID                 1562
#define IDC_STATIC_BOX1                 1563
#define IDC_STATIC_BOX2                 1564
#define IDC_STATIC_BOX3                 1565
#define IDC_ST_KMSYZ                    1566
#define IDC_STATIC10                    1567
#define IDC_STATIC25                    1568
#define IDC_STATIC8                     1569
#define IDC_STATIC9                     1570
#define IDC_SYUK_CHK                    1571
#define IDC_TKYCOMBO                    1572
#define IDC_TKYONLY                     1573
#define IDC_STATICVERS                  2050
#define IDC_STATICCPY                   2051
#define ID_SHOW_MDITABS                 32772
#define ID_BUTTON_F1                    32773
#define ID_BUTTON_F2                    32774
#define ID_BUTTON_F3                    32775
#define ID_BUTTON_F4                    32776
#define ID_BUTTON_F6                    32778
#define ID_BUTTON_F7                    32779
#define ID_BUTTON_F8                    32780
#define ID_BUTTON_F9                    32781
#define ID_BUTTON_F11                   32782
#define ID_BUTTON_F12                   32783
#define ID_BUTTON_END                   32784
#define ID_BUTTON_INSERT                32785
#define ID_BUTTON_DELETE                32786
#define ID_BUTTON_HOME                  32787
#define IDA_RETURN                      32787
#define ID_32790                        32790
#define IDM_INPUTTYPE                   32791
#define ID_Menu                         32795
#define ID_32796                        32796
#define IDM_INDKMK                      32797
#define ID_JGYKMK                       32798
#define IDM_JGYKMK                      32799
#define ID_32800                        32800
#define ID_MENU_KYUCSV                  32801
#define IDM_SWK_COPY                    32802
#define IDM_SWK_PASTE                   32803
#define ID_MENU_SLIP                    32804
#define ID_BUTTON_COSEL                 50002
#define ID_BUTTON_JOBSEL                50003
#define ID_BUTTON_JOB1                  50004
#define ID_BUTTON_JOB2                  50005
#define ID_BUTTON_JOB3                  50006
#define ID_BUTTON_JOB4                  50007
#define ID_BUTTON_JOB5                  50008
#define ID_BUTTON_JOB6                  50009
#define ID_BUTTON_JOB7                  50010
#define ID_BUTTON_JOB8                  50011
#define ID_BUTTON_JOB9                  50012
#define ID_BUTTON_JOB10                 50013
#define ID_BUTTON_JOB11                 50014
#define ID_BUTTON_JOB12                 50015
#define ID_BUTTON_JOB13                 50016
#define ID_BUTTON_JOB14                 50017
#define ID_BUTTON_JOB15                 50018
#define ID_BUTTON_F5                    57607
#define IDS_MSG_STRING                  61446
#define IDS_MSG_STRING2                 61447
#define IDS_MSG_STRING3                 61448
#define IDS_MSG_STRING4                 61449
#define IDS_HUSEN_GUIDE                 61450
#define IDS_ACVAL_GUIDE1                61451
#define IDS_ACVAL_GUIDE2                61452

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        179
#define _APS_NEXT_COMMAND_VALUE         32804
#define _APS_NEXT_CONTROL_VALUE         1388
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
