//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// DBDinp.rc で使用
//
#define IDR_MANIFEST                    1
#define IDC_SWKDEL                      3
#define IDOK2                           3
#define IDC_BTN_DUPLI                   3
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             101
#define IDD_DBDINP_FORM                 102
#define IDD_DNPBASEDLG                  103
#define ID_KENGYOMODE                   104
#define IDR_MAINFRAME                   128
#define IDR_DBDINPTYPE                  129
#define ID_VIEW_THEME_OFFICEXP          130
#define IDC_ACTIVATE                    131
#define IDC_CLOSEDOCUMENT               132
#define IDC_HIDETABS                    133
#define IDR_TAB_POPUP                   134
#define IDC_ALIGNTABTOP                 135
#define IDC_ALIGNTABBOTTOM              136
#define IDC_ALIGNTABLEFT                137
#define IDC_ALIGNTABRIGHT               138
#define IDR_SKEYFRAME                   139
#define IDD_DBBASEVIEW                  141
#define IDD_DNPSELDLG                   142
#define IDB_SKINBITMAP                  143
#define IDR_SCANFRAME                   144
#define IDR_ACBKFRAME                   145
#define IDD_DLG_ACSEL                   146
#define IDB_FURIBITMAP                  147
#define IDD_SYKBN_DLG                   148
#define IDB_NKINBITMAP                  149
#define IDD_TTLDSP                      150
#define IDD_AUTOINP                     151
#define IDD_ENVDIALOG                   152
#define IDR_ACCELERATOR1                153
#define IDB_HUSEN_BMP                   154
#define IDD_TAIDSP                      155
#define IDD_DSPOPT_DLG                  156
#define IDD_BKINP_DLG                   157
#define IDD_DKEY_DLG                    158
#define IDD_MNTH_DLG                    159
#define IDD_HUSEN_DLG                   160
#define IDB_HSBITMAP                    161
#define IDD_SUBDATA_DLG                 162
#define IDD_DLGSIWAKE                   163
#define IDD_MSG_DLG                     164
#define IDD_RDSEL                       165
#define IDD_SELIMG_DLG                  166
#define IDD_SCANKEYFORM                 167
#define IDD_DBABOOK_FORM                168
#define IDD_DBDNPINVIEW                 169
#define IDD_DLG_NSKIN                   170
#define IDD_DLG_DELSWK                  171
#define IDD_DBDINP_FORM1                172
#define IDD_DBABOOK_FORM1               173
#define IDD_DLG_RDREG                   174
#define IDI_ICON_ATTACH                 175
#define IDD_DLG_RDGRPADD                176
#define IDI_ICON_ATTACHED               177
#define IDD_SCAN_FORM                   178
#define IDI_ICON_DISPSLIP               179
#define IDD_DLG_SEQCHG                  180
#define IDD_ACDSPOPT_DLG                181
#define IDI_ICON_PLUR                   182
#define IDR_ACBMENU                     183
#define IDI_ICON_PLURAL_ATTACH          184
#define IDD_ACRDSEL_DLG                 185
#define IDD_DLG_DCOPY                   186
#define IDR_SWKMENU                     187
#define IDD_DLG_RDREMAIN                188
#define IDD_ACINPSUP_DLG                189
#define IDR_DNPCPYMENU                  190
#define IDD_DLG_SELWND                  191
#define IDD_DLG_RDDNP                   192
#define IDD_DLG_RDDNPADD                193
#define IDD_DLG_RDNPFURI                194
#define IDD_DLG_RDNPNSKIN               195
#define IDD_DLG_NPAUTO                  199
#define IDI_ICON_SCAN                   208
#define IDD_DLG_FURI                    210
#define IDI_ICON1                       211
#define IDI_ICON_DOCREAD                211
#define IDD_DLG_DUPLI                   214
#define IDC_ACBOOKLIST                  1000
#define IDC_ALLKEYDEL                   1001
#define IDC_ALT                         1002
#define IDC_BILLINP                     1003
#define IDC_BMN_CHECK                   1004
#define IDC_BMNBRN_REG                  1005
#define IDC_BMNTKBR_CHK                 1006
#define IDC_BMNFIX                      1007
#define IDC_BMNINP_CHK                  1008
#define IDC_BMNNAM_DSP                  1009
#define IDC_BMNSELGRP                   1010
#define IDC_BRN_CPY                     1011
#define IDC_BRN_INPCHK                  1012
#define IDC_BRNNAM_DSP                  1013
#define IDC_BRNTOSWK                    1014
#define IDC_BRNUM                       1015
#define IDC_KJI_INPCHK                  1016
#define IDC_KOJITOSWK                   1017
#define IDC_BRNUMTITLE                  1018
#define IDC_KOJITOSWK2                  1018
#define IDC_BMNTOSWK                    1018
#define IDC_KANKJI_CHK                  1019
#define IDC_BS_CHK                      1020
#define IDC_BSTOTAL                     1021
#define IDC_KJIKMK_CHK                  1022
#define IDC_BSTOTAL_CRE                 1023
#define IDC_BRN_INPCHK2                 1024
#define IDC_BRN_INPKAKU                 1025
#define IDC_BSTOTAL_DEB                 1026
#define IDC_BSTOTALTITLE                1027
#define IDC_BSTOTALTITLE2               1028
#define IDC_BTN_DEL                     1029
#define IDC_BTN_END                     1030
#define IDC_BTN_IKATU                   1031
#define IDC_BTN_NOMDFY                  1032
#define IDC_BTN_OK                      1033
#define IDC_BUTTON_DISP                 1034
#define IDC_BUTTON1                     1035
#define IDC_BUTTON2                     1036
#define IDC_BUTTON3                     1037
#define IDC_BUTTON4                     1038
#define IDC_CHECK_CBM                   1039
#define IDC_CHECK_CBR                   1040
#define IDC_CHECK_CBR2                  1041
#define IDC_CHECK_CKJ                   1042
#define IDC_CHECK_DBM                   1043
#define IDC_CHECK_DBM2                  1044
#define IDC_CHK_INPDATA                 1044
#define IDC_CHECK_TKY                   1045
#define IDC_CHK_INPDATA2                1045
#define IDC_CHK_MDFDATA                 1045
#define IDC_CHECK_DBR                   1046
#define IDC_CHECK_DENP                  1047
#define IDC_CHK_MIKAKUD                 1047
#define IDC_CHECK_DKJ                   1048
#define IDC_CHECK1                      1049
#define IDC_CHECK_DENP2                 1050
#define IDC_CHECK4                      1050
#define IDC_CHECK_KIKAN                 1050
#define IDC_CHECK_SNO                   1051
#define IDC_CHECK_KMSYZ                 1052
#define IDC_CHECK_MNONLY                1053
#define IDC_SELDSP_CHK                  1054
#define IDC_CHK_CONFIRM                 1055
#define IDC_CHECK2                      1056
#define IDC_CHK_MENZEI                  1056
#define IDC_COMBO_STYPE                 1057
#define IDC_CHECK3                      1058
#define IDC_COMBO_MIKAKUD               1058
#define IDC_CHK_HUSEN                   1059
#define IDC_COMBO1                      1060
#define IDC_CREDFIX                     1061
#define IDC_CUSTOM1                     1062
#define IDC_TKY_REPORT                  1063
#define IDC_DATA_USER                   1064
#define IDC_DATANUM                     1065
#define IDC_DATANUMTITLE                1066
#define IDC_DATE_SEL                    1067
#define IDC_DATEFIX                     1068
#define IDC_DEBTFIX                     1069
#define IDC_DEBTOTALTITLE               1070
#define IDC_DEL_SWK                     1071
#define IDC_DENP_COMBO                  1072
#define IDC_DENPMODEGRP                 1073
#define IDC_DISPBIGIMG                  1074
#define IDC_DENP_COMBO2                 1075
#define IDC_SNO_COMBO                   1076
#define IDC_DISPETC                     1077
#define IDC_SNO_GRP                     1078
#define IDC_DISPORDER                   1079
#define IDC_DSP_CRED                    1080
#define IDC_DSP_CRED2                   1081
#define IDC_DSP_DEBT                    1082
#define IDC_DTLIST                      1083
#define IDC_DTLINE                      1084
#define IDC_FIXDATEGRP                  1085
#define IDC_FURI_CHK                    1086
#define IDC_HJIYUTOSWK                  1087
#define IDC_HS_COMBO                    1088
#define IDC_HUSEN1                      1089
#define IDC_HUSEN2                      1090
#define IDC_HUSEN3                      1091
#define IDC_HUSEN4                      1092
#define IDC_HUSEN5                      1093
#define IDC_HUSEN6                      1094
#define IDC_HUSEN7                      1095
#define IDC_HUSENINP                    1096
#define IDC_ICSDBEDT_BMN                1097
#define IDC_ICSDBEDT_BSKMK              1098
#define IDC_ICSDBEDT_DATE               1099
#define IDC_ICSDBEDT_KMK                1100
#define IDC_ICSDBEDT_KASITKY            1100
#define IDC_ICSDBEDT_KOJI               1101
#define IDC_ICSDBEDT_TGNUM              1102
#define IDC_ICSDBEDT_BMON               1103
#define IDC_ICSDBEDT_SYOBRN             1104
#define IDC_ICSDBEDT_SYONUM             1105
#define IDC_ICSDBEDT8CTRL1              1106
#define IDC_ICSDBEDT_KMINP              1107
#define IDC_ICSDBEDTCTRL1               1110
#define IDC_ICSDBEDT_BMON2              1111
#define IDC_ICSDBEDTCTRL2               1112
#define IDC_ICSDBEDT8CTRL3              1113
#define IDC_ICSDBEDTCTRL3               1114
#define IDC_ICSDBEDTCTRL4               1115
#define IDC_ICSDBEDTCTRL5               1116
#define IDC_ICSDIAG8CTRL1               1117
#define IDC_ICSDIAG8CTRL2               1118
#define IDC_ICSDIAG8CTRL3               1119
#define IDC_ICSDISP_SELIMG              1120
#define IDC_ICSDISP_SEQ                 1121
#define IDC_ICSDISP8CTRL1               1122
#define IDC_ICSDISPCTRL1                1123
#define IDC_ICSDISP8CTRL2               1124
#define IDC_ICSDISPCTRL10               1125
#define IDC_ICSDISP8CTRL3               1126
#define IDC_ICSDISPCTRL11               1127
#define IDC_ICSDISPCTRL12               1128
#define IDC_ICSDISPCTRL2                1129
#define IDC_ICSDISPCTRL3                1130
#define IDC_ICSDISPCTRL4                1131
#define IDC_ICSDISPCTRL5                1132
#define IDC_ICSDISPCTRL6                1133
#define IDC_ICSDISPCTRL7                1134
#define IDC_ICSDISPCTRL8                1135
#define IDC_ICSDISPCTRL9                1136
#define IDC_ICSDISPGENKIN               1137
#define IDC_ICSDISPJOB                  1138
#define IDC_ICSDISPRDREMAIN             1139
#define IDC_ICSDISPSYOGT                1140
#define IDC_ICSLISTINPCTRL1             1141
#define IDC_ICSSELCTRL1                 1142
#define IDC_ICSLISTINP_SKIN             1143
#define IDC_ICSSELCTRL2                 1144
#define IDC_ICSSELCTRL3                 1145
#define IDC_IMAGE1                      1146
#define IDC_IMAGE2                      1147
#define IDC_IMAGE3                      1148
#define IDC_IMAGE4                      1149
#define IDC_IMAGE5                      1150
#define IDC_IMAGE6                      1151
#define IDC_IMAGE7                      1152
#define IDC_IMAGE8                      1153
#define IDC_IMGTKYEDIT                  1154
#define IDC_ICSDISPBKMK                 1155
#define IDC_IMPORT_CHK                  1156
#define IDC_KANADISP_CHK                1157
#define IDC_KARITOTAL                   1158
#define IDC_ZEIMDFY_CHK                 1159
#define IDC_KASITOTAL                   1160
#define IDC_DELSWK_CHK                  1161
#define IDC_KM_COMBO                    1162
#define IDC_SCNCLR_CHK                  1163
#define IDC_KMKSELGRP                   1164
#define IDC_KMKSELGRP1                  1165
#define IDC_KMKSELGRP2                  1166
#define IDC_KOJIFIX                     1167
#define IDC_LIST1                       1168
#define IDC_TKYSELGRP                   1169
#define IDC_MNTHSEL                     1170
#define IDC_MOTO_SWK                    1171
#define IDC_SELGUIDE                    1172
#define IDC_NCHK_CBMN                   1173
#define IDC_NCHK_CBRN                   1174
#define IDC_NCHK_CKJI                   1175
#define IDC_NCHK_CRE                    1176
#define IDC_NCHK_DATE                   1177
#define IDC_NCHK_DBCR                   1178
#define IDC_NCHK_DBMN                   1179
#define IDC_NCHK_DBRN                   1180
#define IDC_NCHK_DBT                    1181
#define IDC_NCHK_DCBRN                  1182
#define IDC_NCHK_DENP                   1183
#define IDC_NCHK_DKJI                   1184
#define IDC_NCHK_HUSEN                  1185
#define IDC_NCHK_SEQ                    1186
#define IDC_NCHK_SKBN                   1187
#define IDC_NCHK_SNUM                   1188
#define IDC_NCHK_SEQ2                   1189
#define IDC_NCHK_SNO                    1190
#define IDC_NCHK_TKY                    1191
#define IDC_NCHK_SNUMBER                1192
#define IDC_NCHK_SYKBN                  1193
#define IDC_NCHK_SYZSW                  1194
#define IDC_NCHK_TAI                    1195
#define IDC_NCHK_TGDATE                 1196
#define IDC_NCHK_URISIRE                1197
#define IDC_NCHK_VAL                    1198
#define IDC_NCHK_VAL2                   1199
#define IDC_NCHK_URISIRE2               1200
#define IDC_NCHK_TOKUS                  1201
#define IDC_NCHK_ZEI                    1202
#define IDC_NCHK_ZKBN                   1203
#define IDC_NCHK_ZRITU                  1204
#define IDC_NEW_SWK                     1205
#define IDC_NORMALTOTAL                 1206
#define IDC_NORMALTOTAL_CRE             1207
#define IDC_NORMALTOTAL_DEB             1208
#define IDC_NORMALTOTALTITLE            1209
#define IDC_NYUK_CHK                    1210
#define IDC_OTHER_GRP                   1211
#define IDC_RADIO_SW1                   1212
#define IDC_SYZ_GRP                     1213
#define IDC_RADIO_SW2                   1214
#define IDC_RADIO1                      1215
#define IDC_RADIO2                      1216
#define IDC_RADIO_SKN1                  1217
#define IDC_RADIOBMNSELYES              1218
#define IDC_RADIO_BMN1                  1218
#define IDC_RADIO4                      1219
#define IDC_RADIO_SKN2                  1220
#define IDC_RADIOBMNSELNO               1221
#define IDC_RADIO_BMN2                  1221
#define IDC_RADIO_SKN4                  1222
#define IDC_RADIOKMCODE                 1223
#define IDC_RADIOKMNUM                  1224
#define IDC_RADIOKMKEEP                 1225
#define IDC_RADIOKMTOP                  1226
#define IDC_RADIOSWKTEKYES              1227
#define IDC_RADIOSWKTEKNO               1228
#define IDC_RD_BMNNO                    1229
#define IDC_RADIOSWKTKY1                1230
#define IDC_RD_BMNYES                   1231
#define IDC_RADIOSWKTKY2                1232
#define IDC_RD_BRN                      1233
#define IDC_RD_DATE                     1234
#define IDC_RD_DENPNO                   1235
#define IDC_RD_DENPYES                  1236
#define IDC_RD_KOJINO                   1237
#define IDC_RD_KOJIYES                  1238
#define IDC_RD_LNHT1                    1239
#define IDC_CHK_TKYTYPE2                1240
#define IDC_RD_LNHT2                    1241
#define IDC_RD_SYONO                    1242
#define IDC_CHK_VALNOT                  1243
#define IDC_RD_SYOYES                   1244
#define IDC_CHK_ZMVDATE                 1245
#define IDC_RD_TGDTNO                   1246
#define IDC_RD_TGDTYES                  1247
#define IDC_RDLBL_CMBO                  1248
#define IDC_RD_HJIYUYES                 1249
#define IDC_RDLIST                      1250
#define IDC_RD_HJIYUNO                  1251
#define IDC_NCHK_DCBMN                  1252
#define IDC_RGDATA_GRP                  1253
#define IDC_SCANLIST                    1254
#define IDC_SCN_DATESEL                 1255
#define IDC_NCHK_DCKJI                  1256
#define IDC_VALCPY_GRP                  1257
#define IDC_TKYREG_GRP                  1258
#define IDC_ZMOVE_GRP                   1259
#define IDC_NCHK_INVNO                  1260
#define IDC_NCHK_INVNO2                 1261
#define IDC_NCHK_MENZEI                 1261
#define IDC_SCNSEQ1                     1300
#define IDC_SCNSEQ2                     1301
#define IDC_SCNDOCSEQ1                  1302
#define IDC_SCNDATE1                    1302
#define IDC_SCNDOCSEQ2                  1303
#define IDC_SCNDATE2                    1303
#define IDC_SCNBMON1                    1304
#define IDC_SCNBMON2                    1305
#define IDC_SCNCBMN1                    1306
#define IDC_SCNCBMN2                    1307
#define IDC_SCNKOJI1                    1308
#define IDC_SCNKOJI2                    1309
#define IDC_SCNCKJI1                    1310
#define IDC_SCNCKJI2                    1311
#define IDC_SCNDEBT                     1312
#define IDC_SCNDEBT2                    1313
#define IDC_SCNDBR1                     1314
#define IDC_SCNDBR2                     1315
#define IDC_SCNCRED                     1316
#define IDC_SCNCRED2                    1317
#define IDC_SCNCBR1                     1318
#define IDC_SCNCBR2                     1319
#define IDC_SCNDBCR                     1320
#define IDC_SCNDBCR2                    1321
#define IDC_SCNDCBR1                    1322
#define IDC_SCNDCBR2                    1323
#define IDC_SCNDENP1                    1324
#define IDC_SCNDENP2                    1325
#define IDC_SCNVAL1                     1326
#define IDC_SCNVAL2                     1327
#define IDC_SCNZEI1                     1328
#define IDC_SCNZEI2                     1329
#define IDC_SCNTAIKA1                   1330
#define IDC_SCNTAIKA2                   1331
#define IDC_SCNTKY                      1332
#define IDC_SCNTKY2                     1333
#define IDC_SCNINVNO                    1333
#define IDC_SCNINVNODISP                1334
#define IDC_SCNSNUM1                    1335
#define IDC_SCNSNUM2                    1336
#define IDC_SCNSNO1                     1337
#define IDC_SCNSNO2                     1338
#define IDC_SCNDCBMN1                   1339
#define IDC_SCNDCBMN2                   1340
#define IDC_SCNDCKJI1                   1341
#define IDC_SCNDCKJI2                   1342
#define IDC_SCN_INVNO                   1343
#define IDC_SCN_INVNODISP               1344
#define IDC_SCN_INVNO2                  1345
#define IDC_SCN_INVNO2DISP              1346
#define IDC_SCNTDAT1                    1347
#define IDC_SCNTDAT2                    1348
#define IDC_SCNHUCMT                    1349
#define IDC_ACRDLIST                    1388
#define IDC_ST_BASEKMK                  1389
#define IDC_ST_TLKMK                    1390
#define IDC_ST_KMKNAM                   1391
#define IDC_ST_BUMON                    1392
#define IDC_ST_TLKOJI                   1393
#define IDC_ST_BRN                      1394
#define IDC_ST_TLBRN                    1395
#define IDC_ST_LINE                     1396
#define IDC_SCNHUSEN                    1400
#define IDC_SCNHJIYU                    1401
#define IDC_SCNHJIYU2                   1402
#define IDC_SCNSKBN                     1403
#define IDC_SCNSKBN2                    1404
#define IDC_SCNSYZSW                    1405
#define IDC_SCNSYZSW2                   1406
#define IDC_SCNTOKUS                    1407
#define IDC_SCNTOKUS2                   1408
#define IDC_SCNURISIRE                  1409
#define IDC_SCNURISIRE2                 1410
#define IDC_SCNZRITU                    1411
#define IDC_SCNZRITU2                   1412
#define IDC_SCNNOINPBRN                 1413
#define IDC_SPIN1                       1414
#define IDC_SCNSYZKTSN                  1415
#define IDC_SPIN2                       1416
#define IDC_TKYTAB_GRP                  1417
#define IDC_ST_BMN                      1418
#define IDC_DNPTYPE_GRP                 1418
#define IDC_SCNGYOKBN                   1419
#define IDC_KANATYPE_GRP                1419
#define IDC_ST_BMNGRP                   1420
#define IDC_SCNSHTKBN                   1421
#define IDC_SYZSTOP_GRP                 1421
#define IDC_SCNSHTTYP                   1422
#define IDC_ST_BRNGRP                   1423
#define IDC_ST_CBMN                     1424
#define IDC_ST_CBR                      1425
#define IDC_ST_CKJ                      1426
#define IDC_ST_CRED                     1427
#define IDC_ST_DATE                     1428
#define IDC_ST_DBCR                     1429
#define IDC_ST_DBMN                     1430
#define IDC_ST_DBR                      1431
#define IDC_ST_DBMN2                    1432
#define IDC_ST_DCBR                     1433
#define IDC_ST_DEBT                     1434
#define IDC_ST_DENP                     1435
#define IDC_ST_DENP2                    1436
#define IDC_ST_DEBT_INVNO               1436
#define IDC_ST_DKJ                      1437
#define IDC_ST_DUSER                    1438
#define IDC_ST_TKBRNGRP                 1439
#define IDC_ST_DUSER2                   1439
#define IDC_ST_DATMKAKU                 1439
#define IDC_ST_FIXGRP                   1440
#define IDC_ST_SNO                      1441
#define IDC_ST_HJIYU                    1442
#define IDC_ST_HUSEN                    1443
#define IDC_ST_KOJI                     1444
#define IDC_ST_LNHT                     1445
#define IDC_ST_NOIPBRN                  1446
#define IDC_ST_ORDER                    1447
#define IDC_ST_SEQ                      1448
#define IDC_ST_SKBN                     1449
#define IDC_ST_SNUM                     1450
#define IDC_ST_STYPE                    1451
#define IDC_ST_SWKSEL                   1452
#define IDC_ST_SEQ2                     1453
#define IDC_ST_SYONO                    1454
#define IDC_ST_SYZSW                    1455
#define IDC_ST_BLKMOVE                  1456
#define IDC_ST_TAIKA                    1457
#define IDC_ST_GRP                      1458
#define IDC_ST_TDAT                     1459
#define IDC_ST_DATA                     1460
#define IDC_ST_TGDT                     1461
#define IDC_ST_GRPCNT                   1462
#define IDC_ST_TKYTAB                   1463
#define IDC_ST_GYOKBN                   1464
#define IDC_ST_DATACNT                  1465
#define IDC_ST_SHTKBN                   1466
#define IDC_ST_SHTTYP                   1467
#define IDC_ST_CONFIRM                  1468
#define IDC_ST_TKY                      1469
#define IDC_ST_URISIRE                  1470
#define IDC_ST_VAL                      1471
#define IDC_ST_ZEI                      1472
#define IDC_ST_CONFIRM2                 1472
#define IDC_ST_URISIRE2                 1473
#define IDC_ST_SYZ                      1473
#define IDC_SCNHUSEN2                   1474
#define IDC_ST_ZRITU                    1475
#define IDC_STATIC_BOX1                 1476
#define IDC_STATIC_BOX2                 1477
#define IDC_STATIC_BOX3                 1478
#define IDC_STATIC_KARA                 1479
#define IDC_ST_KMSYZ                    1480
#define IDC_ST_TOKUS                    1481
#define IDC_STATIC_MSG                  1482
#define IDC_ST_KMSYZ2                   1483
#define IDC_STATIC_POS                  1484
#define IDC_STATIC_POS2                 1485
#define IDC_STATIC_WAK                  1486
#define IDC_STATIC_WAK2                 1487
#define IDC_STATIC_WAK3                 1488
#define IDC_STATIC_WAK4                 1489
#define IDC_STATIC_WAK5                 1490
#define IDC_STATIC_WAK6                 1491
#define IDC_STATIC_WAK7                 1492
#define IDC_STATIC_WAK8                 1493
#define IDC_STATIC1                     1494
#define IDC_STATIC_WAK10                1495
#define IDC_STATIC_WAK11                1496
#define IDC_ST_TLBMON                   1496
#define IDC_STATIC29                    1497
#define IDC_STATIC24                    1498
#define IDC_STATIC_WAK9                 1499
#define IDC_STATIC30                    1499
#define IDC_STATIC28                    1500
#define IDC_STATIC10                    1501
#define IDC_STATIC31                    1501
#define IDC_STATIC11                    1502
#define IDC_STATIC12                    1503
#define IDC_STATIC13                    1504
#define IDC_STATIC14                    1505
#define IDC_STATIC15                    1506
#define IDC_STATIC16                    1507
#define IDC_STATIC17                    1508
#define IDC_STATIC18                    1509
#define IDC_STATIC19                    1510
#define IDC_STATIC2                     1511
#define IDC_STATIC20                    1512
#define IDC_STATIC21                    1513
#define IDC_STATIC3                     1514
#define IDC_STATIC4                     1515
#define IDC_STATIC5                     1516
#define IDC_STATIC6                     1517
#define IDC_STATIC7                     1518
#define IDC_ST_TYPE                     1519
#define IDC_STATIC32                    1519
#define IDC_STATIC26                    1520
#define IDC_STATIC25                    1521
#define IDC_STATIC_TKY1                 1522
#define IDC_STATIC8                     1523
#define IDC_BTN_INIT                    1524
#define IDC_STATIC_TKY2                 1525
#define IDC_STATIC9                     1526
#define IDC_STATIC_TKYGD                1527
#define IDC_SWKTEKGRP                   1528
#define IDC_SWKTEKGRP2                  1529
#define IDC_SYO_BUZZER                  1530
#define IDC_SYOBRN_DSP                  1531
#define IDC_SYOG_SAGAK                  1532
#define IDC_SYOBRN_DSP2                 1533
#define IDC_BRNSEL_KANA                 1534
#define IDC_CHK_VALCOPY                 1535
#define IDC_SYO_BUZZER2                 1536
#define IDC_STATIC_LINE                 1537
#define IDC_SCAN_KMCD                   1538
#define IDC_SYOGBS                      1539
#define IDC_CHK_TKYTYPE1                1540
#define IDC_SYOGBSTITLE                 1541
#define IDC_CHK_TKYTYPE3                1542
#define IDC_SYOGTOTAL                   1543
#define IDC_CHK_ZMVZANC                 1544
#define IDC_SYOGTOTAL_CRE               1545
#define IDC_CHK_ZMVZANC2                1545
#define IDC_CHK_ENDKAKU                 1545
#define IDC_SWTKYDGRP                   1546
#define IDC_SYOGTOTAL_DEB               1547
#define IDC_SYOGTOTALTITLE              1548
#define IDC_SYUK_CHK                    1549
#define IDC_TKYCOMBO                    1550
#define IDC_TKYONLY                     1551
#define IDC_VALTITLE                    1552
#define IDC_VALTITLEBASE                1553
#define IDC_WANING                      1554
#define IDC_ST_DCBMN                    1555
#define IDC_WANING2                     1556
#define IDC_CHK_CONMDFY                 1557
#define IDC_ICSDBEDT_TGDATE             1558
#define IDC_CHK_KAZEI                   1558
#define IDC_ICSDBEDT_TGNO               1559
#define IDC_ST_DCKJ                     1560
#define IDC_ICSDBEDT_HUSEN              1561
#define IDC_ST_INVNO                    1561
#define IDC_RD_ZEIYES                   1562
#define IDC_RD_ZEINO                    1563
#define IDC_STATIC22                    1564
#define IDC_RD_SYZYES                   1564
#define IDC_STATIC_GRP                  1565
#define IDC_RD_ZEINO2                   1565
#define IDC_RD_SYZNO                    1565
#define IDC_CHK_TKYTAB                  1566
#define IDC_NOWDATA                     1567
#define IDC_CHK_TKYTAB2                 1567
#define IDC_CHK_DNPTYPE                 1567
#define IDC_RD_VALCHK                   1568
#define IDC_CHK_DNPTYPE2                1568
#define IDC_CHK_KMKANA                  1568
#define IDC_RD_VALCHK2                  1569
#define IDC_SCROLLBAR1                  1569
#define IDC_CHK_SYZSTOP                 1569
#define IDC_BTN_GRPADD                  1570
#define IDC_DISPSLIP_CHK                1571
#define IDC_PROGRESS_RECCNT             1572
#define IDC_LINKSLIP_BTN                1573
#define IDC_STATIC_MESSAGE_1            1574
#define IDC_DISPSLIP_BTN                1575
#define IDC_STATIC23                    1576
#define IDC_DISPSLIP_BTN2               1576
#define IDC_GNPSCAN_BTN                 1576
#define IDC_RD_DISPDATE                 1577
#define IDC_EDIT1                       1577
#define IDC_RD_DISPSEQ                  1578
#define IDC_CHK_ZEIRITSU                1578
#define IDC_RD_NOFIX                    1579
#define IDC_ST_SIKIN                    1579
#define IDC_RD_SKINFIX                  1580
#define IDC_ST_AUTO                     1580
#define IDC_RD_NKINFIX                  1581
#define IDC_ST_SIKINDBT                 1581
#define IDC_BUTTON_ALL                  1581
#define IDC_STATIC_GUID                 1582
#define IDC_ST_SIKINCRE                 1582
#define IDC_CHECK_MENZEI                1582
#define IDC_STATIC27                    1583
#define IDC_ST_SIKINDBT2                1583
#define IDC_STATIC_WAKU                 1583
#define IDC_BTN_REGDNP                  1584
#define IDC_ST_SIKINCRE2                1584
#define IDC_CHK_CNO                     1584
#define IDC_BTN_DNPSET                  1585
#define IDC_CHK_BMN                     1585
#define IDC_ST_TOROK                    1586
#define IDC_CHK_KOJI                    1586
#define IDC_ST_GRPNAME                  1587
#define IDC_CHK_TKY                     1587
#define IDC_BTN_CHGNAM                  1588
#define IDC_BTN_DNPDEL                  1589
#define IDC_BTN_REGOVW                  1590
#define IDC_ST_RDNPLABEL                1591
#define IDC_BTN_DNPDEL2                 1592
#define IDC_BTN_CONTXT                  1593
#define IDC_RADIO_FURI1                 1594
#define IDC_RADIO_FURI2                 1595
#define IDC_RTSWKKANA_CHK               1596
#define IDC_RADIO_DNPCHK                1597
#define IDC_RADIO_DNPCHK2               1598
#define IDC_RADIO_DNPCHK3               1599
#define IDC_SCNMENWARI                  1600
#define IDC_SCNMENWARI2                 1601
#define IDC_STATICVERS                  2050
#define IDC_STATICCPY                   2051
#define ID_SHOW_MDITABS                 32772
#define ID_BUTTON_F1                    32773
#define ID_BUTTON_F2                    32774
#define ID_BUTTON_F3                    32775
#define ID_BUTTON_F4                    32776
#define ID_BUTTON_F6                    32778
#define ID_BUTTON_F7                    32779
#define ID_BUTTON_F8                    32780
#define ID_BUTTON_F9                    32781
#define ID_BUTTON_F11                   32782
#define ID_BUTTON_F12                   32783
#define ID_BUTTON_END                   32784
#define ID_BUTTON_INSERT                32785
#define ID_BUTTON_DELETE                32786
#define ID_BUTTON_HOME                  32787
#define IDA_RETURN                      32787
#define ID_32790                        32790
#define IDM_INPUTTYPE                   32791
#define ID_Menu                         32795
#define ID_32796                        32796
#define IDM_INDKMK                      32797
#define ID_JGYKMK                       32798
#define IDM_JGYKMK                      32799
#define ID_32800                        32800
#define ID_MENU_KYUCSV                  32801
#define IDM_SWK_COPY                    32802
#define IDM_SWK_PASTE                   32803
#define ID_MENU_SLIP                    32804
#define IDM_LINE_COPY                   32804
#define IDM_LINE_PASTE                  32805
#define ID_MENU_GENCSV                  32805
#define ID_BUTTON_SHINCYOKU             32806
#define IDM_REGDATA                     32807
#define IDM_REGDLGUSE                   32808
#define ID_Menu32815                    32815
#define ID_Menu32816                    32816
#define ID_LINE_DELETE                  32817
#define ID_MENU_WIZ                     32817
#define IDM_LINE_DELETE                 32818
#define IDM_HELP_DISP                   32888
#define ID_BUTTON_COSEL                 50002
#define ID_BUTTON_JOBSEL                50003
#define ID_BUTTON_JOB1                  50004
#define ID_BUTTON_JOB2                  50005
#define ID_BUTTON_JOB3                  50006
#define ID_BUTTON_JOB4                  50007
#define ID_BUTTON_JOB5                  50008
#define ID_BUTTON_JOB6                  50009
#define ID_BUTTON_JOB7                  50010
#define ID_BUTTON_JOB8                  50011
#define ID_BUTTON_JOB9                  50012
#define ID_BUTTON_JOB10                 50013
#define ID_BUTTON_JOB11                 50014
#define ID_BUTTON_JOB12                 50015
#define ID_BUTTON_JOB13                 50016
#define ID_BUTTON_JOB14                 50017
#define ID_BUTTON_JOB15                 50018
#define ID_BUTTON_F5                    57607
#define IDS_MSG_STRING                  61446
#define IDS_MSG_STRING2                 61447
#define IDS_MSG_STRING3                 61448
#define IDS_MSG_STRING4                 61449
#define IDS_HUSEN_GUIDE                 61450
#define IDS_ACVAL_GUIDE1                61451
#define IDS_ACVAL_GUIDE2                61452
#define IDS_DTINS_GUIDE                 61453
#define IDS_MSG_WIZSWK                  61454

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        217
#define _APS_NEXT_COMMAND_VALUE         32818
#define _APS_NEXT_CONTROL_VALUE         1585
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
